<!DOCTYPE html>
<html>
<head>
<title>Beacon Patient Care Privacy Policy</</title>
</head>
<body>

<p><strong>Updated On: October 10, 2020</strong></p>
<p><strong>Beacon Patient Care Privacy Policy</strong></p>
<p>Beacon Patient Care, (&ldquo;Beacon Patient Care,&rdquo; &ldquo;we&rdquo; or &ldquo;us&rdquo;) values your privacy. Beacon Patient Care offers telemedicine platform and Services (the &ldquo;Services&rdquo;). This Telehealth Privacy Policy applies to our website https://beaconpatientcare.com (the &ldquo;Site&rdquo;), as well as the Services, which are accessible through the Site and Beacon Patient Care Android App. Through our Services participating medical professionals and healthcare staff (&ldquo;Healthcare Providers&rdquo; or &ldquo;Providers&rdquo;) can provide health care services online to their clients and patients (&ldquo;Patients&rdquo;). In this Privacy Policy (&ldquo;Policy&rdquo;), we describe how we collect, use, and disclose information that we obtain about visitors to our Site and users of our Services.</p>
<p>By visiting the Site or using our Services, you agree that your personal information will be handled as described in this Policy. Your use of our Site and Services, and any dispute over privacy is subject to this Policy and our Terms of Service, including its applicable limitations on damages and the resolution of disputes. The Beacon Patient Care Terms of Service are incorporated by reference into this Policy.</p>
<p>&nbsp;</p>
<p><strong>WHAT INFORMATION DO WE COLLECT ABOUT YOU AND WHY?</strong></p>
<p>We may collect information about you directly from you and from third parties, as well as automatically through your use of our Site or Services.</p>
<p><strong>Information We Collect Directly From You.</strong></p>
<p>Users may browse the informational areas of the Site without registering with. However, registration is required to use the Services. Once a Healthcare Provider has registered with us and subscribed to our Services, the Healthcare Provider can then invite Patients to use the Services. After receiving an invite, the Patient would then need to register for a Beacon Patient Care account to use the Services.</p>
<p>Healthcare Provider Registration. To register, Healthcare Providers must provide certain information about themselves and their practices including: the Healthcare Provider&rsquo;s name, date of birth, gender, address, email, mobile and work phone; the Healthcare Provider&rsquo;s practice name, address, phone number and fax number; and a user id and password.&nbsp; We may also collect certain optional information, including: middle name or initial, bank account or other payment information and other contact details, picture and communication preferences.</p>
<p>Patient Registration.&nbsp; Patients must provide certain information, including: name, date of birth, gender, address, email, mobile and work phone, as well as a user id and password.&nbsp; We may also collect certain optional information, including: middle name or initial, home phone and other contact info, pharmacy name and contact details, other demographic information, health insurance information, credit card number and billing details, picture and communications preferences.&nbsp; In addition, the Patient can communicate other health-related information to the Healthcare Provider during a video consultation via the Beacon Patient Care app.</p>
<p><strong>Other.</strong>&nbsp; We also collect other information that you submit on our Site, such as comments and blog postings (see &ldquo;User Generated Content&rdquo; section below).&nbsp; You must submit your name to post a comment to our blog and you may submit other optional information as well.</p>
<p>&nbsp;</p>
<p>Information We Collect From Healthcare Providers.&nbsp; Certain features and Services are available to patients because their Healthcare Providers use our Services. Healthcare Providers may provide patient names and e-mail addresses to us so we may communicate with patients on their behalf about the availability of certain Services.</p>
<p>Information We Collect Automatically. We may automatically collect the following information about your use of our Site or Services through cookies, web beacons, and other technologies: your domain name; your browser type and operating system; web pages you view; links you click; your IP address; a time and date stamp and the length of time you visit our Site and or use our Services; the referring URL, or the webpage that led you to our Site; and your browser type. We may combine this information with other information that we have collected about you, including, where applicable, your user name, name, and other personal information. Please see the section &ldquo;Our Use of Cookies and Other Tracking Mechanisms&rdquo; below for more information about our use of cookies and other tracking mechanisms.</p>
<p><strong>HOW WE USE YOUR INFORMATION</strong></p>
<p>We use the information that we gather about you for the following purposes:</p>
<p><strong>To provide our Services.</strong></p>
<ul>
<li>To communicate with you about your use of our Services, to respond to your inquiries, to provide technical support and assistance and for other customer service purposes.</li>
<li>To communicate with you regarding the availability of Services on behalf of your Healthcare Provider, otherwise, we do not market to Patients.</li>
<li>To send you reminders and other information related to your care on behalf of your Healthcare Provider.</li>
<li>To tailor the content and information that we may send or display, to offer location customization, and personalized help and instructions, and to otherwise personalize your experiences while using the Site or our Services.</li>
<li>To send offers and other promotional communications to Healthcare Providers;</li>
<li>To display advertising on our Site.</li>
<li>To better understand how users access and use our Services, both on an aggregated and individualized basis, in order to improve our Site and Services and respond to user desires and preferences, and for other research and analytical purposes.</li>
</ul>
<p><strong>HOW WE SHARE YOUR INFORMATION</strong></p>
<p>We may share the information that we collect about you, including personally identifiable information, as follows:</p>
<p>Healthcare Providers. As a Patient, your information will be shared with Healthcare Providers as directed and consented to by you. Our Services make your Assessments and related information available to your Healthcare Provider.&nbsp;&nbsp; We will not make information available to Healthcare Providers other than those with whom you have requested that we share your Assessments.&nbsp; This Policy does not address how Healthcare Providers will use and disclose information obtained using Beacon Patient Care.&nbsp; If you would like this information, you should ask your Healthcare Provider directly for a copy of his/her Notice of Privacy Practices.</p>
<p><strong>Service Providers.</strong> We may disclose the information we collect from you to third party vendors, service providers, contractors or agents who perform functions on our behalf.</p>
<p><strong>Business Transfers.</strong> If we are acquired by or merged with another company, if substantially all our assets are transferred to another company, or if we are a part of a bankruptcy proceeding, we may transfer the information we have collected from you to the other Company.</p>
<p><strong>In Response to Legal Process.</strong> We also may disclose the information we collect from you in order to comply with the law, a judicial proceeding, court order, or other legal process, such as in response to a subpoena in compliance with applicable privacy laws.</p>
<p><strong>To Protect Us and Others.</strong> We also may disclose the information we collect from you, to the extent permitted by law, where we believe it is necessary to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the safety of any person, violations of our Terms of Use or this Policy, or as evidence in litigation in which Beacon Patient Care is involved.</p>
<p><strong>Aggregate and De-Identified Information.</strong> We may share aggregate or de-identified information about users with third parties for marketing, advertising, research or similar purposes.</p>
<p><strong>OUR USE OF COOKIES AND OTHER TRACKING MECHANISMS</strong></p>
<p>We use cookies and other tracking mechanisms to track information about your use of our Site or Services. We may combine this information with other information we collect from you.</p>
<p><strong>Cookies.</strong>&nbsp; Cookies are alphanumeric identifiers that we transfer to your computer&rsquo;s hard drive through your web browser for record-keeping purposes. Some cookies allow us to make it easier for you to navigate our Site and Services, while others are used to enable a faster log-in process or to allow us to track your activities at our Site and Service.&nbsp; Most web browsers automatically accept cookies, but if you prefer, you can edit your browser options to block them in the future. The Help portion of the toolbar on most browsers will tell you how to prevent your computer from accepting new cookies, how to have the browser notify you when you receive a new cookie, or how to disable cookies altogether. Visitors to our Site who disable cookies will be able to browse public areas of the Site, but the Services will not function.</p>
<p><strong>Clear GIFs</strong> (a.k.a. web beacons, web bugs or pixel tags).&nbsp; Clear GIFs are tiny graphics with a unique identifier, similar in function to cookies. In contrast to cookies, which are stored on your computer&rsquo;s hard drive, clear GIFs are embedded invisibly on web pages. We may use clear GIFs (in connection with our Site to, among other things, track the activities of Site visitors, help us manage content, and compile statistics about Site usage. We and our third party service providers also use clear GIFs in HTML e-mails to our customers, to help us track e-mail response rates, identify when our e-mails are viewed, and track whether our e-mails are forwarded.</p>
<p><strong>Third Party Analytics.</strong> We use automated devices and applications, such as Google Analytics, MixPanel, and Kissmetrics, to evaluate usage of our Site and Services and to help us personalize content on out Site and Services. We also may use other analytic means to evaluate our Services. We use these tools to help us improve our Services, performance and user experiences. These entities may use cookies and other tracking technologies to perform their services. We do not share your personal information with these third parties.</p>
<p><strong>Advertising</strong>. We may use network advertisers, such as AdRoll, to advertise our Site and Services on other websites, and we may do so based on your visits to our Site and to other third party Sites. These entities may use cookies and other tracking technologies to perform their services. We do not share your personal information with these third parties.&nbsp; Our Site does not currently respond to browser &ldquo;Do-Not-Track requests; however, you may find out more about targeted advertising in general, and opt out of targeted ads from many ad networks, including AdRoll, through the National Advertising Initiative (&ldquo;NAI&rdquo;) website, or the Digital Advertising Alliance (&ldquo;DAA&rdquo;) website.</p>
<p><strong>USER GENERATED CONTENT</strong></p>
<p>We may invite you to post content on our Site, including your comments Beacon Patient Care cannot prevent such information from being used in a manner that may violate this Policy, the law, or your personal privacy.&nbsp; As a result, you should never post any sensitive information to our Site that you are not comfortable sharing publicly (e.g., personal medical details).&nbsp; Beacon Patient Care is not liable to you or any other person for any content or information you post to our Site or the use or disclosure of such content or information by other users or third parties.</p>
<p><strong>THIRD-PARTY LINKS</strong></p>
<p>Our Site and Services may contain links to third-party websites. Any access to and use of such linked websites is not governed by this Policy, but instead is governed by the privacy policies of those third party websites. We are not responsible for the information practices of such third party websites.</p>
<p><strong>PATIENT HEALTH INFORMATION</strong></p>
<p>The privacy and security of Patients&rsquo; individually identifiable health information provided to Beacon Patient Care in connection with Services may be protected by federal law and state privacy laws, because Beacon Patient Care provides Services to health care providers.&nbsp; This health information is &ldquo;protected health information&rdquo; (&ldquo;PHI&rdquo;).&nbsp; PHI may be used and disclosed by Beacon Patient Care as necessary to provide Services, for our own management and operations, to meet our legal obligations, and for any other purpose for which Patients have given consent.&nbsp; We may share PHI with third parties for these purposes in compliance with applicable law.&nbsp; We may de-identify PHI and aggregate it for purposes of monitoring and improving our products and services, for benchmarking purposes, and to provide customized services or technologies our customers.</p>
<p><strong>SECURITY OF MY PERSONAL INFORMATION</strong></p>
<p>We have implemented reasonable technical, physical, administrative, and organizational safeguards to protect the information we collect from loss, misuse, and unauthorized access, disclosure, alteration, and destruction.&nbsp; Please be aware that despite our efforts, no data security measures can guarantee 100% security.&nbsp; You should take steps to protect against unauthorized access to your password, phone, and computer by, among other things, signing off after using a shared computer, choosing a robust password that nobody else knows or can easily guess, and keeping your log-in and password private. We are not responsible for any lost, stolen, or compromised passwords or for any activity on your account via unauthorized password activity.</p>
<p><strong>Access To My Personal Information&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong></p>
<p>You may modify registration information that you have submitted by logging into your account and updating your profile information. Please note that copies of information that you have updated, modified or deleted may remain viewable in cached and archived pages of the Site for a period of time.</p>
<p>&nbsp;</p>
<p><strong>MARKETING EMAILS</strong></p>
<p>We may send periodic promotional or informational emails to Healthcare Providers. Healthcare Providers may opt-out of such communications by following the opt-out instructions contained in the e-mail. Please note that it may take up to 10 business days for us to process opt-out requests. If you opt-out of receiving emails about recommendations or other information we think may interest you, we may still send you e-mails about your account or any Services you have requested or received from us.</p>
<p><strong>CONTACT US</strong></p>
<p>We encourage you to contact us if you have any questions or concerns regarding the privacy aspects of our Services or would like to make a complaint. You may write us at info@beaconpatientcare.com or Beacon Business Centre, 9/B/2, Toynbee Circular Road, Motijheel, Dhaka, Attention: Privacy Officer.</p>
<p><strong>CHANGES TO THIS POLICY</strong></p>
<p>This Policy is current as of the Effective Date set forth above. We may change this Policy from time to time, so please be sure to check back periodically. We will post any changes to this Policy on this page. If we make any changes to this Policy that materially affect our practices with regard to the personal information we have previously collected from you, we will endeavour to provide you with notice in advance of such change, such as by highlighting the change on our Site, or emailing the email address of record for your account.</p>
<p>&nbsp;</p>

</body>
</html>
